sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-652.pdf --upload --lsstdoc LDM-652.tex --env=travis --ltd-product ldm-652"
env:
  global:
    # LSST the Docs credentials
    - secure: "hmwu8Jhy27lVmPN8NATHjba/giYi3afRlNaiHxd4duN85222dSJS2T05NFXIA3Dm9fk/hUGUME2fZpApyknYQuExIlHWclteeh82HZ3+IIgVbTq6KH5YvSymwlRBKl8tkPAy1lsGkNvprZMFUQdyNZ0qM+jmyEOKmy9NIs8jUvtuoY5AJ96hzjnehbqfn44vejdW56rK0Wui4S3YF2QxSME4lh49/oFJ108Mzq1atr2qlFcZKrpXhT+alfw/Y35DrqsBjTrDywpT66jy1EzkuY0Fr6UdBDiHEAXKjWWUK+CTvTRHeiAAGtdc6a5b9eMtrNMa3UnxPWzsMDHVHXEXC0ud5drZ+i61D/5AqvgN7EHKotklHXyAZ0VCyKtEuLJi2jI+IZn/9xO/91dCq2k8oo7oeSWvmUvh7ZCfH7sekwgrz88qr1O8X7Ln4+waxzEZZ9GMnEbIdE2ja8GLhmrx2PXcP5PNuIe9q0tVgkL+lBTesqQc5TUJZbodA2qxqf0CSzWjsNOxWVfwWNRLshySwNFLzsGySwh9tUD5bBXiv0qDg7WBs4cje9L/x86pEm5PqeyxqhnxNpns5iidgvytrp2jz10AVDZXUhGToubnatiHLzpczyVdngTHH/VplZG/AcIXP5Zvmy4KRLJP7dS6ymR4aBSYZAZCTahQjyP8YSI="
    - secure: "sazT3TO1SnnX221bg9yPGldIdcohYqZhAbWMFBKTGWh7EPZC6zREfuiWaUBRJdAnHHTK7hLNXcF2P2w5ATPsKvTCDNDcyZxcYoTCKYvSZ//anCNOThyMDUyLyponrTZUAdz+ChMTmZSFqL2t8jfuFSgKes9r85/373pHdbZ01UmcN+kSg22C8x3vg9Wk6hfzBfPQymEtZBoKG4Rn3t+bx378HuWyIWmejFNIsBKqV6OtDzK8c6pwvb07g1sS3a0crvF1MhI3DwZVBYvpQsPIIeAVPUeANR2dSTP8kapfNtehi7maVbpnpHXv0qJ0KzFiiiEqYxY1uU395chlw5uxxCZVUFmO2flpAdA3+Q7kETFpD0qcDHiuxagAt3UgnEkMt/rlDK/2GiC4P5WTUdJ9vue65MBuOoww+HUWbgQ0/4//fTgoqgoDUMChAc4i68MYulmzimkZCG+ICUw8eWClCwa5SXpsTZQpy4lC62kGvTRnGYNu4yS5VPkSEGUGmy68YPbwGR8UxmnBNmmbxdfucMFMakSNzoB3KlZ/qi3lMAPyigM0OyhNxtcJLwrUFtw9BpyYHh5KJ6KsgYX8lf64tMuZND8GohiaiHBMvYqD40ykQy4eKdZpUcQPoMKDqkQDzNp4Q9ljca4Ful8+TJ2YB/CyJ/JJOkHcG1KunF/+1WM="
